/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  TimeTrackerCsvGroup,
  TimeTrackerCsvItem,
} from './classes/time-tracker-item';

export namespace Components {
  interface TtApp {}
  interface TtTimelineInterval {
    'interval': TimeTrackerCsvItem;
  }
  interface TtTimelineItem {
    'item': TimeTrackerCsvGroup;
    'start': Date;
  }
  interface TtTimelineList {
    'items': TimeTrackerCsvItem[];
  }
}

declare global {


  interface HTMLTtAppElement extends Components.TtApp, HTMLStencilElement {}
  var HTMLTtAppElement: {
    prototype: HTMLTtAppElement;
    new (): HTMLTtAppElement;
  };

  interface HTMLTtTimelineIntervalElement extends Components.TtTimelineInterval, HTMLStencilElement {}
  var HTMLTtTimelineIntervalElement: {
    prototype: HTMLTtTimelineIntervalElement;
    new (): HTMLTtTimelineIntervalElement;
  };

  interface HTMLTtTimelineItemElement extends Components.TtTimelineItem, HTMLStencilElement {}
  var HTMLTtTimelineItemElement: {
    prototype: HTMLTtTimelineItemElement;
    new (): HTMLTtTimelineItemElement;
  };

  interface HTMLTtTimelineListElement extends Components.TtTimelineList, HTMLStencilElement {}
  var HTMLTtTimelineListElement: {
    prototype: HTMLTtTimelineListElement;
    new (): HTMLTtTimelineListElement;
  };
  interface HTMLElementTagNameMap {
    'tt-app': HTMLTtAppElement;
    'tt-timeline-interval': HTMLTtTimelineIntervalElement;
    'tt-timeline-item': HTMLTtTimelineItemElement;
    'tt-timeline-list': HTMLTtTimelineListElement;
  }
}

declare namespace LocalJSX {
  interface TtApp extends JSXBase.HTMLAttributes<HTMLTtAppElement> {}
  interface TtTimelineInterval extends JSXBase.HTMLAttributes<HTMLTtTimelineIntervalElement> {
    'interval'?: TimeTrackerCsvItem;
  }
  interface TtTimelineItem extends JSXBase.HTMLAttributes<HTMLTtTimelineItemElement> {
    'item'?: TimeTrackerCsvGroup;
    'start'?: Date;
  }
  interface TtTimelineList extends JSXBase.HTMLAttributes<HTMLTtTimelineListElement> {
    'items'?: TimeTrackerCsvItem[];
  }

  interface IntrinsicElements {
    'tt-app': TtApp;
    'tt-timeline-interval': TtTimelineInterval;
    'tt-timeline-item': TtTimelineItem;
    'tt-timeline-list': TtTimelineList;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


